### ISSUE TITLE
[Bug]: No module named 'loguru'

### ISSUE THREAD

**Issue by emeraldminer299** [sd-webui/stable-diffusion-webui#1547]
### What happened?

For about a month now and me trying to fix it myself, I've had the same error message everytime even after installing the dependencies manually "No module named 'loguru'". And it also completely breaks stable diffusion webui. Honestly my entire build seems screwed because for some reason it wants me to merge environment.yaml even though the only change I made to it was changing ldm to ldo so it works.\

But also setting it back to factory settings and reinstalling doesn't fix it.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
--no-half --precision full

optimized_turbo = True
```

### Relevant log output

```shell
Relauncher: Launching...
Traceback (most recent call last):
  File "C:\Users\[Username]\stable-diffusion-webui\scripts\webui.py", line 20, in <module>
    from logger import logger, set_logger_verbosity, quiesce_logger
  File "C:\Users\[Username]\stable-diffusion-webui\scripts\logger.py", line 3, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Relauncher: Process is ending. Relaunching in 1s...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
Should be fixed on master with #1550 

The environment might need to be recreated if the simple update won't help.

**Comment by emeraldminer299** [comment]
@codedealer I reinstalled it again but I still have the same issues. What do you think?

So simple updates wasn't enough.

**Comment by OFF-AI** [comment]
I just had this issue.

1. I had to install pip
2. I had to install all the modules asked for through pip
3. Then uninstall the app which needed the modules
4. Reinstall the app - WITH ALL THE MODULES ALLREADY PRESENT ON MY PC

Number 4 is key. No download, import, moving files, changing directories, cashe directory change or registry changes made it for me. Reason i don´t specify all the steps I did is because this can be applied on many different apps and modules. And for installing pip and modules - there are good guides out there. Better than I can make.
