### ISSUE TITLE
[Bug]: No module named 'cv2' - linux install

### ISSUE THREAD

**Issue by Zaithe** [sd-webui/stable-diffusion-webui#869]
### What happened?

after launching the linux-setup.sh and going through the script to configure my launch arguments i finish inputting the arguments then it gets stuck in a loop looking for the cv2 environment in conda which doesn't exist. 

```
Do you want to create a public xxxxx.gradi.app URL to allow others to uses your interface? (Requires properly forwarded ports)
1) Yes
2) No
#? 1
Setting Ultimate Stable Diffusion to open a public share URL...


Customization of Ultimate Stable Diffusion is complete. Continuing...

Running linux-setup.sh...

EnvironmentNameNotFound: Could not find conda environment: lsd
You can list all discoverable environments with conda info --envs.


Relauncher: Launching...
Traceback (most recent call last):
  File "/home/zaithe/Desktop/stable-diffusion-webui-master/stable-diffusion-webui/scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 1
Relauncher: Launching...
Traceback (most recent call last):
  File "/home/zaithe/Desktop/stable-diffusion-webui-master/stable-diffusion-webui/scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 2

```

When i run conda info --envs it shows the below:
```
zaithe@zaithe-Alienware-linux:~/Desktop/stable-diffusion-webui-master$ conda info --envs
# conda environments:
#
base                     /home/zaithe/anaconda3

```

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Linux

### Relevant log output

```shell
Do you want to create a public xxxxx.gradi.app URL to allow others to uses your interface? (Requires properly forwarded ports)
1) Yes
2) No
#? 1
Setting Ultimate Stable Diffusion to open a public share URL...


Customization of Ultimate Stable Diffusion is complete. Continuing...

Running linux-setup.sh...

EnvironmentNameNotFound: Could not find conda environment: lsd
You can list all discoverable environments with conda info --envs.


Relauncher: Launching...
Traceback (most recent call last):
  File "/home/zaithe/Desktop/stable-diffusion-webui-master/stable-diffusion-webui/scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 1
Relauncher: Launching...
Traceback (most recent call last):
  File "/home/zaithe/Desktop/stable-diffusion-webui-master/stable-diffusion-webui/scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 2




zaithe@zaithe-Alienware-linux:~/Desktop/stable-diffusion-webui-master$ conda info --envs
# conda environments:
#
base                     /home/zaithe/anaconda3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoshuaKimsey** [comment]
This happened due to your conda env likely not being installed right. I just updated my script to handle this issue. Download the new update, and run it again. It should work you through updating the repo and rebuilding the conda environment.

**Comment by Zaithe** [comment]
> This happened due to your conda env likely not being installed right. I just updated my script to handle this issue. Download the new update, and run it again. It should work you through updating the repo and rebuilding the conda environment.

Hi Joshua,
Thanks for your reply. I reran the script and reset the parameters and updated however I'm still getting the below error.

```
conda: command not found
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 1
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 2
```


I think it has something to do with it saying `conda: command not found` but when i type conda in terminal it works fine.

**Comment by kwaad2** [comment]
I'm getting this exact same error. I however am running windows. Same error on both main, and dev branches.

`Relauncher: Launching...
Traceback (most recent call last):
  File "C:\STABLE DIFFUSION\stable-diffusion-webui-dev\scripts\webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...`

Still running an old version from the 5th, and it still works perfectly.
So I can confirm, that my environment does work properly, and it's apparently not exclusive to Linux.

**Comment by harjoat** [comment]
> 

I'm getting the exact same error on both Windows and Linux.

**Comment by bcowan** [comment]
I was fighting with the same issue, and for me at least, it turned out to be that my default shell is FISH, and the Anaconda install didn't set the path up for that. When I ran linux-setup.sh in BASH, the problem went away. (It also did a lot more stuff.)

After that, I ran into an issue where the setup hung "installing pip dependencies". That seemed to be linked to pip not being able to deal with pre-existing dependencies. Adjusting the environment with,

export PIP_EXISTS_ACTION=w

and then running linux-setup.sh again ran to completion, and resulted in a working system.  With any luck this will work for others too.

**Comment by kwaad2** [comment]
This appears to be resolved (for me at least) with the latest changes on master.

**Comment by JoshuaKimsey** [comment]
Yeah, some people have had pip issues, both myself and @hlky ran into this as well at different points, on different systems. I think the solution was just to delete the `stable-diffusion-webui` folder, delete the conda environment (on Linux run `conda env remove -n lsd`), and then reinstall. That is what I had to do to get past the hung pip dependency issue. I think hlky mentioned the same thing.

**Comment by xeb** [comment]
I receive this error when trying to build with Docker (I am running Ubuntu 22.04.1 LTS). After a fresh repository clone, moving `.env_docker.example` to `.env_docker` (and enabling the suggested options), I get the following after running `docker-compose up` and the container builds:

```
sd                  |                                                                                                                                                                     
sd                  | Validating model files...                                                                                                                                          
sd                  | checking model.ckpt...                                                                                                                                             
sd                  | model.ckpt is valid!                                                                                                                                               
sd                  |                                                                                                                                                                    
sd                  | checking GFPGANv1.3.pth...                                                                                                                                         
sd                  | GFPGANv1.3.pth is valid!                                                                                                                                           
sd                  |                                                                                                                                                                    
sd                  | checking RealESRGAN_x4plus.pth...                                                                                                                                  
sd                  | RealESRGAN_x4plus.pth is valid!                                                                                                                                    
sd                  |                                                                                                                                                                    
sd                  | checking RealESRGAN_x4plus_anime_6B.pth...                                                                                                                         
sd                  | RealESRGAN_x4plus_anime_6B.pth is valid!                                                                                                                           
sd                  |                                                                                                                                                                    
sd                  | entrypoint.sh: Launching with arguments --gpu=1 --esrgan-gpu=1 --gfpgan-gpu=1                                                                                      
sd                  | Traceback (most recent call last):                                                                                                                                 
sd                  |   File "/sd/scripts/webui.py", line 3, in <module>                                                                                                                 
sd                  |     import cv2                                                                                                                                                     
sd                  | ModuleNotFoundError: No module named 'cv2'                            
sd                  | entrypoint.sh: Process is ending. Relaunching in 0.5s...                                                                                                           
sd                  | entrypoint.sh: Launching with arguments --gpu=1 --esrgan-gpu=1 --gfpgan-gpu=1                                                                                      
sd                  | Relaunch count: 1                                                                                                                                                  
sd                  | Traceback (most recent call last):                                                                                                                                 
sd                  |   File "/sd/scripts/webui.py", line 3, in <module>                                                                                                                 
sd                  |     import cv2                                                                                                                                                     
sd                  | ModuleNotFoundError: No module named 'cv2'                                                                                                                         
sd                  | entrypoint.sh: Process is ending. Relaunching in 0.5s...                                                                                                           
sd                  | entrypoint.sh: Launching with arguments --gpu=1 --esrgan-gpu=1 --gfpgan-gpu=1                                                                                      
sd                  | Relaunch count: 2                                                                                                                                                  
sd                  | Traceback (most recent call last):                                    
sd                  |   File "/sd/scripts/webui.py", line 3, in <module>                                                                                                                 
sd                  |     import cv2                                                        
sd                  | ModuleNotFoundError: No module named 'cv2'               
```

**Comment by mapleroyal** [comment]
@JoshuaKimsey the issue is not resolved, I've got it on 10 different fresh Manjaro installs over the last 3 days. Here's how I replicate it:
> fresh manjaro install
> download Anaconda3-2022.05-Linux-x86_64.sh
> place it in home directory, run it, and accept default install location
> reboot machine after anaconda install
> download linux-sd.sh and sd-v1-4.ckpt  to home directory
> make linux-sd.sh executable and run it
> choose launch arguments when asked
> 1, 2, 1, 2, 1, 2

`Customization of Ultimate Stable Diffusion is complete. Continuing...

Generating linux-setup.sh in ./stable-diffusion-webuiRunning linux-setup.sh...Could not find conda environment: lsd
You can list all discoverable environments with `conda info --envs`.

Relauncher: Launching...
Traceback (most recent call last):
  File "/home/stdiff/stable-diffusion-webui/scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
        Relaunch count: 1
Relauncher: Launching...
Traceback (most recent call last):
  File "/home/stdiff/stable-diffusion-webui/scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
        Relaunch count: 2`

**Comment by kevcx2** [comment]
I am experienced this issue due to the conda env not being setup correctly.

My conda installation cannot find many of the packages required in enviornment.yaml

@mapleroyal @xeb @Zaithe - 

What envs do you see if you run `conda env list`

What is the output if you run the following command from the stable-diffusion-webui folder:

`conda env update --file environment.yaml`?

--------

@JoshuaKimsey On my Ubuntu machine, if I run `conda search pytorch`, for example, I don't see the required version on any channels (1.11.0). I tried adding `conda-forge` and `conda-forge/label/broken`.

I tried pinning the the closest available versions but that created lots of conflicts and still prevented the conda env from being built.

I am on the following machine: Canonical, Ubuntu, 22.04 LTS, arm64

**Comment by mapleroyal** [comment]
@kevcx2 I stopped messing with it and went over to this one https://github.com/AUTOMATIC1111/stable-diffusion-webui so I can't test anything out for this. I'm looking forward to a fix though, because this is the version I prefer.

**Comment by JoshuaKimsey** [comment]
@mapleroyal Yeah, this doesn't appear to be so much an issue with my script as it is something going wrong with the conda installation. You will know if conda is working because when you open a new terminal, you should see `(base)` at the very start of your termianl prompt. It looks like this:
`(base) jkimsey@pop-os:~ `

When you activate a conda env, you will see `(base)` turn to the name of the conda environment. If you do `conda env list` you'll see which one's you have installed. If you can do that, I might be able to figure out exactly where the issue is.

@kevcx2 I'm also not sure what's going on, but do make sure you've activated the conda env first before you try to install pip packages, or else it won't apply to the env and vice versa. Otherwise, I really don't know why that would be happening, as that would be a part of how conda is installing the necessary dependencies, which is kinda outside the scope of my script currently. I just call conda to set it up, conda should handle everything on its own.

**Comment by dpanic** [comment]
I had the same problem. 
Ubuntu 22.04
Default shell is ZSH. Tried with ZSH and Bash. Same problem.

What do you want me to run in order to debug and solve this?

**Comment by judokusq** [comment]
I had the same issue.
The Problem was me not installing/understanding Anaconda right. I installed Anaconda as mentioned on their Website with their Script.
It is very important to close your Terminal after installing Anaconda (as the Script tells you when finished) and relaunch a new one. 
You should see a `(base)` in front of your Username in your Terminal.
Then run the `linux-sd.sh` script again.

**Comment by kevcx2** [comment]
@dpanic 

What envs do you see if you run `conda env list`?

What is the output if you run the following command from the stable-diffusion-webui folder:
`conda env update --file environment.yaml`?

**Comment by kevcx2** [comment]
@JoshuaKimsey Thanks for the help -- if I run `conda env list` I only see base. The conda env isn't installing because it can't resolve the dependencies listed in `environment.yaml`.

What linux os do you use? Im curious if you run `conda search pytorch`, do you see v1.11.0 listed? conda can't find that package on my machine which is preventing the env from installing.

**Comment by dpanic** [comment]
```
conda env list
# conda environments:
#
base                  *  /home/dpanic/anaconda3
lsd                      /home/dpanic/anaconda3/envs/lsd
````

```
conda env update --file environment.yaml


Successfully installed GFPGAN clip k-diffusion latent-diffusion-0.0.1 realesrgan taming-transformers-0.0.1

done
#
# To activate this environment, use
#
#     $ conda activate lsd
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done
```

I use Ubuntu 22.04

**Comment by kevcx2** [comment]
I resolved the issue for myself. The issue originally was a failed conda env installation. The underlying issue was that I was on an AWS machine with an ARM cpu. The required packages are **only** available on x86_64 architecture.

**Comment by dpanic** [comment]
> I resolved the issue for myself. The issue originally was a failed conda env installation. The underlying issue was that I was on an AWS machine with an ARM cpu. The required packages are **only** available on x86_64 architecture.

I am on x86_64 architecture. Only difference which I can see is that on Ubuntu 22.04 there is Python 3.10.4 by default while anaconda package is for 3.9

**Comment by codedealer** [comment]
@dpanic are you trying to run the environment with python 3.10 or are you installing python 3.9 inside the conda env? And a follow up have you installed pip dependencies outside of virtual environments? Because that can cause conflicts in conda as well.

**Comment by dpanic** [comment]
@codedealer  all what I did is I installed by manual provided on this GitHub repo. 
I haven't installed manualy any pip dependencies outside of virtual environment.

**Comment by Zaithe** [comment]
Thank you, this is now working for me.

**Comment by mathis-r** [comment]
I had the same problem yesterday when I used the script (I am on Fedora 36), but I managed to fix it:

First I removed ./stable-diffusion-webui, then every part of anaconda (~/.conda & ~/anaconda, and the PATH variable on .bashrc)

After that I installed conda from the package manager (dnf in my case), and I ran the script another time.

It worked just fine.

It's maybe because I didn't install anaconda from their website, or because the script was fixed meanwhile.

**Comment by CarlQLange** [comment]
Just a small note that the `linux-sd.sh` script presently uses bash, and so if you're a `zsh` or other shell user, you may need to make sure conda is initialised in the bash shell with `conda init bash`.

**Comment by dpanic** [comment]
> Just a small note that the `linux-sd.sh` script presently uses bash, and so if you're a zsh or other shell user, you may need to make sure conda is initialised in the bash shell with `conda init bash`.

Thanks @CarlQLange ```conda init bash``` solved the issue.

So my suggestion is let's update how-to for Linux install:
- linux-sd.sh is required to be run through bash shell
- conda init bash is required step
- python version needs to be aligned with conda (python3.9)

**Comment by JoshuaKimsey** [comment]
@dpanic Yes, I'll do so. I guess I didn't think about that, as I though the Conda initializaing happened in a more universal way, but y'all are right, if someone uses zsh, it would break that. I don't know or use zsh, so I'll just add instructions to use it in bash only.

Can you call bash from zsh? If so, I might just be able to make a presumptive bash call initially to ensure the environment is already in Bash before running.

**Comment by usernamex** [comment]
This fixed my issue:

1. conda env list
2. conda activate <environment name>

**Comment by bobbypfreely** [comment]
@JoshuaKimsey I'm getting this error as well, my conda is installed correctly, I get the base or ldm before anything in the terminal. Wsl2 with the latest Ubuntu, everything is freshly installed and correctly, this is a thorn for sure, was there ever a definite fix?
